version: '2'

services:
  es_master:
    image: elasticsearch:5.3
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./es-master.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    restart: always
  
  es_node1:
    image: elasticsearch:5.3
    links:
      - es_master
    volumes:
      - ./data1:/usr/share/elasticsearch/data
      - ./es-node.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - NODE_NAME=data-node1
    restart: always

  es_node2:
    image: elasticsearch:5.3
    links:
      - es_master
    volumes:
      - ./data2:/usr/share/elasticsearch/data
      - ./es-node.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - NODE_NAME=data-node2
    restart: always

  es_node3:
    image: elasticsearch:5.3
    links:
      - es_master
    volumes:
      - ./data3:/usr/share/elasticsearch/data
      - ./es-node.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - NODE_NAME=data-node3
    restart: always

  kibana:
    image: kibana:5.3
    ports:
      - 5601:5601
    links:
      - es_master:elasticsearch
    depends_on:
      - es_master

  eshead:
    image: mobz/elasticsearch-head:5
    ports:
      - 9100:9100
    depends_on:
      - es_master